<a href="https://colab.research.google.com/github/sgl13/PythonLearning/blob/main/Day18_Pandas_and_NumPy_data_manipulation__ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas**:

Indexing, element access via .at[], feature engineering (column math), missing value handling with .fillna(), grouping with .agg(), merging, and concatenation.

**NumPy**:

Reshaping arrays, fancy indexing (corner extraction), structured arrays sorting, and masked arrays using numpy.ma

In [26]:
import pandas as pd
import numpy as np

# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")
print(df)

# Set the index to be the first column
df.set_index('A', inplace=True)
print("DataFrame with new index:")
print(df)

Original DataFrame:
    A   B   C   D
0   8  18  51   7
1  32  16  15  91
2  34  48  52  67
3   1  92  15  94
4  94   2  53  64
5  33  27   1   9
DataFrame with new index:
     B   C   D
A             
8   18  51   7
32  16  15  91
34  48  52  67
1   92  15  94
94   2  53  64
33  27   1   9


In [27]:
#Create a Pandas DataFrame with specified columns and index
df = pd.DataFrame(np.random.randint(1, 100, size=(3, 3)), columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print("Original DataFrame:")
print(df)

# Access the element at row 'Y' and column 'B'
element = df.at['Y', 'B']
print("Element at row 'Y' and column 'B':", element)

Original DataFrame:
    A   B   C
X  78  54  11
Y  77  47  61
Z  67  36  39
Element at row 'Y' and column 'B': 47


In [28]:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
print(df)

# Add a new column that is the product of the first two columns
df['D'] = df['A'] * df['B']
print("DataFrame with new column:")
print(df)


Original DataFrame:
    A   B   C
0  26  70  60
1  33  78  24
2  64  87   2
3  79  11  87
4  85  22  50
DataFrame with new column:
    A   B   C     D
0  26  70  60  1820
1  33  78  24  2574
2  64  87   2  5568
3  79  11  87   869
4  85  22  50  1870


In [29]:
# Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
print(df)

# Introduce some NaN values
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print("DataFrame with NaN values:")
print(df)

# Fill the NaN values with the mean of the respective columns
df.fillna(df.mean(), inplace=True)
print("DataFrame with NaN values filled:")
print(df)

Original DataFrame:
    A   B   C
0  70  75   3
1   8  99  52
2  46  50  38
3  73  54  44
4  13  71  78
DataFrame with NaN values:
      A     B     C
0  70.0   NaN   3.0
1   8.0  99.0  52.0
2  46.0  50.0   NaN
3  73.0  54.0  44.0
4   NaN  71.0  78.0
DataFrame with NaN values filled:
       A     B      C
0  70.00  68.5   3.00
1   8.00  99.0  52.00
2  46.00  50.0  44.25
3  73.00  54.0  44.00
4  49.25  71.0  78.00


In [30]:
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

# Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category
grouped = df.groupby('Category')['Value'].agg(['sum', 'mean'])
print("Grouped DataFrame:")
print(grouped)

Original DataFrame:
  Category  Value
0        A     12
1        C     90
2        C     31
3        B     62
4        C      9
5        C     77
6        C     88
7        C     47
8        A      6
9        C      8
Grouped DataFrame:
          sum  mean
Category           
A          18   9.0
B          62  62.0
C         350  50.0


In [31]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'], 'Value1': np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E'], 'Value2': np.random.randint(1, 100, size=4)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

# Merge the DataFrames using the common column
merged = pd.merge(df1, df2, on='Key')
print("Merged DataFrame:")
print(merged)

DataFrame 1:
  Key  Value1
0   A      58
1   B      90
2   C       5
3   D      53
DataFrame 2:
  Key  Value2
0   A      35
1   B      61
2   C      96
3   E      63
Merged DataFrame:
  Key  Value1  Value2
0   A      58      35
1   B      90      61
2   C       5      96


In [32]:
# Create two Pandas DataFrames with different columns
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

# Concatenate the DataFrames along the rows
concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
print(concat_rows)

# Concatenate the DataFrames along the columns
concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
print(concat_columns)

DataFrame 1:
    A   B
0  28  14
1  23  72
2  95  78
DataFrame 2:
    C   D
0  32  25
1  66  96
2  22  38
Concatenated DataFrame (rows):
      A     B     C     D
0  28.0  14.0   NaN   NaN
1  23.0  72.0   NaN   NaN
2  95.0  78.0   NaN   NaN
0   NaN   NaN  32.0  25.0
1   NaN   NaN  66.0  96.0
2   NaN   NaN  22.0  38.0
Concatenated DataFrame (columns):
    A   B   C   D
0  28  14  32  25
1  23  72  66  96
2  95  78  22  38


In [33]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [34]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[16 12  5  2  7]
 [ 5 13 15  3  5]
 [ 8 17  9  8  9]
 [18 14  3  2 14]
 [16  5  2  2  4]]
Corner elements:
[16  7 16  4]


In [35]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [37]:
import numpy.ma as ma
# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 7  8 17  3]
 [ 3  1 16 20]
 [16  7  7 11]
 [ 2 13 13  2]]
Masked array:
[[7 8 -- 3]
 [3 1 -- --]
 [-- 7 7 --]
 [2 -- -- 2]]
Sum of unmasked elements: 40
