<a href="https://colab.research.google.com/github/sgl13/PythonLearning/blob/main/Day11_Array%26Vectors_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to NumPy**

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on them efficiently.

**Array (ndarray)**

A NumPy Array is a grid of values, all of the same data type (homogeneous), indexed by a tuple of non-negative integers.

Dimensions are called axes.

Shape is a tuple showing the size along each axis.

**Vector**

A Vector is a 1-dimensional (1D) array. It represents a sequence of numbers stored in a single row or column.

In [2]:
import numpy as np

In [22]:
#check the version of the version
import numpy as np
print(np.__version__)

2.0.2


In [4]:
# To perform element-wise multiplication between two lists, you could
# use a for loop.
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] * list_b[i])

list_c

[2, 8, 18]

**universal fuction**


In [23]:
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


**array slicing and indexing**

In [24]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr[0]

array([1, 2, 3, 4])

In [26]:
arr[0][0]

np.int64(1)

In [27]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [28]:
print(arr[0][0])
print(arr[1:,1:3])

1
[[ 6  7]
 [10 11]]


In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

**modiefy array elements**

In [30]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


**the central object in numpy array's**

In [32]:
l = [1,2,3,4,5,6]
#create an array from above the list
a = np.array(l)
print(a)
#find the shape of the array
print(a.shape)
#find the dimension of the array
print(a.ndim)
#find the number of elements in the array
print(a.size)
#find the element data types from above the array
print(a.dtype)
#find the each element size in bytes
print(a.itemsize)

[1 2 3 4 5 6]
(6,)
1
6
int64
8


In [33]:
a = np.array([1,2,3])
b = np.array([4])
print(a+b)
"""broadcasting method is a powerful mechanism where single element of an array adds with multiple or
differant size of another array"""

[5 6 7]


'broadcasting method is a powerful mechanism where single element of an array adds with multiple or \ndifferant size of another array'

In [34]:
#dot product / inner product - vector multiplication of 2 arrays and sum of the result
#what is the rule to apply dot product on 1D array?
#the arrays must be in same size
a = np.array([1,2])
b = np.array([3,4])
d = np.dot(a,b)
print(d)

11


In [35]:
c = a@b
print(c)

11


In [36]:
#can we create an array from set of numbers
s = {1,2,3,4,5,6}
import numpy as np
a = np.array(s)
print(a)
print(type(a))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
#print first row from above array
#syntax -->> array[row_index,column_index]
#array[s:e:step,s:e:step]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(a[0])

[1 2 3]


In [39]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
#print 6 from above array
print(a[1,1])

6


In [41]:
#convert rows into columns and columns into rows--> transpose #changing dimension of data
print(a.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [42]:
#find the diaogonal element in the array "a"
print(np.diag(a))

[ 1  6 11]


In [43]:
#dot product in 2d array means nothing matrix cross multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
print(np.dot(a,b))

[[13 16]
 [29 36]]


In [44]:
a = np.array([10,21,16,15,17,18,20])
#check the elements in the above array even or odd
print(a%2==0)

[ True False  True False False  True  True]


In [45]:
a = np.array([10,21,16,15,17,18,20])
print(a>20)

[False  True False False False False False]


In [46]:
a = np.array([10,21,16,15,17,18,20])
print(np.where(a%2==0,a,-1))

[10 -1 16 -1 -1 18 20]


In [47]:
#print the indexes where the condition is true
#np.argwhere(logic)
print(np.argwhere(a%2==0))

[[0]
 [2]
 [5]
 [6]]


In [48]:
#concatination of array's
#np.concat((arr1,arr2),axis=0/1))
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concat((a,b),axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [49]:
#Hstac:- adds sequence of array horizentally
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
#Vstack:- adds sequence of array vertically
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
#copying of an array's
a = np.array([1,2,3])
b = a.copy()
b[1]=6
print(a)
print(b)
#np.copy() :- if we make changes in the new array it won't impact on old array

[1 2 3]
[1 6 3]


In [52]:
#generate an array of zeros with 2row and 3 columns
#syntax:- np.zeros((rows,column))
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
#syntax:- np.ones((rows,column))
#generate an array of ones with 2row and 3 columns
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
#generate an array of specific number (6) with 2row and 3 columns
#syntax:- np.full((rows,col),number)
c = np.full((2,3),6)
print(c)

[[6 6 6]
 [6 6 6]]


In [55]:
#generate an array of identity matrix
#syntax:- np.eye()
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [56]:
#split an a range of array in to "n" equal parts
#syntax:- np.linspace(start,end,partitions)
e = np.linspace(0,10,5)
print(e)

[ 0.   2.5  5.   7.5 10. ]


In [57]:
# generate an array of random numbers that is uniformly distributed
a = np.random.random((2,3))
print(a)

[[0.02767727 0.26315794 0.76450166]
 [0.03193233 0.68163869 0.20717457]]


In [58]:
#generate an array that is normally distributed
#q) when we suppose to say a data is normally distributed?
#when the mean(avg) is equal to zero and standard deviation is eual to 1
b = np.random.randn(10,5)
print(b)

[[ 1.24608704  1.17338346 -0.39253403  1.22713403  0.51107459]
 [-1.73247319  0.55251195  0.75588122 -0.11779835  0.03934279]
 [ 0.60797966  1.28602793  0.49915408  0.11302807  1.26394094]
 [ 0.00945238  1.96355805  1.67022727 -0.59170124  1.678755  ]
 [ 0.73070694  0.88530905  1.50558744 -1.33148393 -0.17526906]
 [-0.59992275 -0.00516791  1.52799432 -0.380808    0.66082374]
 [ 1.66154948 -0.15211025 -1.47262496  0.28972097 -0.79390595]
 [-0.14785806  1.70405445 -1.01948028  0.94470394  1.18285783]
 [-1.54083962  1.10996878  1.68106487  0.78115602  0.22230025]
 [ 0.03628922 -1.80505962  2.06849684 -0.24670939 -0.92834291]]


In [59]:
b = np.random.randn(10,5)
print(b.mean(),b.std())

-0.15724873642219286 1.1256978722658857


In [60]:
#generate an random integer with 3rows and 3columns
c = np.random.randint(1,10,size=(3,3))
print(c)

[[5 5 9]
 [4 5 6]
 [5 3 8]]


In [61]:
#generate arrange of array
d = np.arange(1,10)
print(d)

[1 2 3 4 5 6 7 8 9]


In [62]:
#statastical concept Normalization
#mean 0 and standard deviation 1
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
print("Mean",mean)
median = np.median(data)
print("Median",median)
variance = np.var(data)
print("variance",variance)
std_dev = np.std(data)
print("Standard deviation",std_dev)

Mean 5.5
Median 5.5
variance 8.25
Standard deviation 2.8722813232690143


In [64]:
#logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])

In [65]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>=5]

array([ 5,  6,  7,  8,  9, 10])

In [5]:
# NumPy arrays let you perform array operations.

# Import numpy, aliased as np.
import numpy as np

# Convert lists to arrays.
array_a = np.array(list_a)
array_b = np.array(list_b)

# Perform element-wise multiplication between the arrays.
array_a * array_b

array([ 2,  8, 18])

**Basic array operations**

In [7]:
# The np.array() function converts an object to an ndarray
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [8]:
# Arrays can be indexed.
x[-1] = 5
x

array([1, 2, 3, 5])

In [9]:
# Trying to access an index that doesn't exist will throw an error.
x[4] = 10

IndexError: index 4 is out of bounds for axis 0 with size 4

In [10]:
# Arrays cast every element they contain as the same data type.
arr = np.array([1, 2, 'coconut'])
arr

array(['1', '2', 'coconut'], dtype='<U21')

In [11]:
# NumPy arrays are a class called `ndarray`.
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
# The dtype attribute returns the data type of an array's contents.
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [13]:
# The shape attribute returns the number of elements in each dimension
# of an array.
arr.shape

(3,)

In [14]:
# The ndim attribute returns the number of dimensions in an array.
arr.ndim

1

In [15]:
# Create a 2D array by passing a list of lists to np.array() function.
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
# Create a 3D array by passing a list of two lists of lists to np.array() function.
arr_3d = np.array([[[1, 2, 3],
                   [3, 4, 5]],

                  [[5, 6, 7],
                   [7, 8, 9]]]
)

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [17]:
# The reshape() method changes the shape of an array.
arr_2d = arr_2d.reshape(2, 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# Create new array
arr = np.array([1, 2, 3, 4, 5])

# The mean() method returns the mean of the elements in an array.
np.mean(arr)

np.float64(3.0)

In [19]:
# The log() method returns the natural logarithm of the elements in an array.
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [20]:
# The floor() method returns the value of a number rounded down
# to the nearest integer.
np.floor(5.7)

np.float64(5.0)

In [21]:
# The ceil() method returns the value of a number rounded up
# to the nearest integer.
np.ceil(5.3)

np.float64(6.0)