In [ ]:
#what is numpy?
#it is a core library for scientific computing in python
#the central object in numpy is "numpy Array's"
#dafine numpy array's?
#Array's are high performance multidimentional structure designed specifically for mathematical operations

In [ ]:
#how many types of numpy array's?
#there are 3 types
#1D- arrauy bwith the rows (axis 0 ) and no columns
#2D - array --> an array with both the rows and column
#3D or multidimentional  Array

#what are all differant use cases of arthimatic operation achived from numpy?
#dot product/inner product
#matrix multiplication
#broadcasting method
#inverse
#solving the linear system
#choosing the random numberes
#statastics


#Installation of numpy


In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip


In [2]:
#check the version of the version
import numpy as np
print(np.__version__)

2.3.5


In [3]:
l = [1,2,3,4,5,6]
#create an array from above the list
a = np.array(l)
print(a)
#find the shape of the array
print(a.shape)
#find the dimension of the array
print(a.ndim)
#find the number of elements in the array
print(a.size)
#find the element data types from above the array
print(a.dtype)
#find the each element size in bytes
print(a.itemsize)

[1 2 3 4 5 6]
(6,)
1
6
int64
8


In [4]:
#create 2 arrays with the same aize apply addition operation 2 arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
#when we add 2 array's of same size is known as vector addition

[5 7 9]


In [5]:
a = np.array([1,2,3])
b = np.array([4])
print(a+b)
"""broadcasting method is a powerful mechanism where single element of an array adds with multiple or 
differant size of another array"""

[5 6 7]


'broadcasting method is a powerful mechanism where single element of an array adds with multiple or \ndifferant size of another array'

In [9]:
#dot product / inner product - vector multiplication of 2 arrays and sum of the result
#what is the rule to apply dot product on 1D array?
#the arrays must be in same size
a = np.array([1,2])
b = np.array([3,4])
d = np.dot(a,b)
print(d)

11


In [7]:
c = a@b
print(c)

11


In [ ]:
#create an array from tuple --->> (1,2,3,4,5,6)
#create an array with set of number-->>{1,2,3,4,5,6}
#create an array from dictionary-->>{"name":"ds","batch":"12")